########################################################
### Mysql
########################################################
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/releaseon_app?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
spring.datasource.username=releaseon_app
spring.datasource.password=releaseon_app123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

########################################################
### Java Persistence Api
########################################################
# Specify the DBMS
spring.jpa.database = MYSQL
# Show or not log for each sql query
spring.jpa.show-sql = true
# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto = update

############################################################
#
# 上传文件大小
#
############################################################
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=300MB
# 对象存储配置
# 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
storage.active=local
# 本地对象存储配置信息
storage.local.storagePath=storage
# 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
storage.local.address=http://127.0.0.1/fetch/
# 阿里云对象存储配置信息
storage.aliyun.endpoint=oss-cn-shenzhen.aliyuncs.com
storage.aliyun.accessKeyId=111111
storage.aliyun.accessKeySecret=xxxxxx
storage.aliyun.bucketName=releaseon_app
# 腾讯对象存储配置信息
# 请参考 https://cloud.tencent.com/document/product/436/6249
storage.tencent.secretId=AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
storage.tencent.secretKey=XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
storage.tencent.region=ap-shanghai
storage.tencent.bucketName=vytech-1300096589
# 七牛云对象存储配置信息
storage.qiniu.endpoint=http://pd5cb6ulu.bkt.clouddn.com
storage.qiniu.accessKey=111111
storage.qiniu.secretKey=xxxxxx
storage.qiniu.bucketName=releaseon_app

# 自定义配置
server.port=8081
config.debug=debug
server.domain=127.0.0.1
admin.username=admin
admin.password=admin123456